version: '2.3'
services:
  classbot:
    command: "errbot"
    build:
      context: ".."
    image: "spkane/classbot:dev"
    networks:
      - dev-net
    volumes:
      - ./config.py:/home/errbot/config.py
      - ./data:/home/errbot/data
      - ./plugins:/home/errbot/plugins
networks:
  dev-net:
    driver: bridge

